version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 9090:9090
    environment:
      - spring_datasource_url=jdbc:h2:mem:minsait
      - spring_datasource_driverClassName=org.h2.Driver
      - spring_datasource_username=minsait
      - spring_datasource_password=minsait
      - spring_jpa_show-sql=true
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.H2Dialect
      - spring_jpa_hibernate_dll-auto=update
      - spring_h2_console_enabled=true
      - spring_h2_console_path=/h2
      - spring_jpa_defer-datasource-initialization=true
      - spring_sql_init_mode=always
volumes:
  pgdata: {}